# nc.yaml
apiVersion: apps/v1
kind: Deployment  # 디플로이먼트 정의
metadata:
  name: nextcloud-deployment
spec:
  replicas: 3  # 레플리카셋의 크기를 3으로 설정
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:apache  # nextcloud:apache 이미지를 사용
          ports:
            - containerPort: 80  # 컨테이너는 TCP/80 포트를 노출
          env:  # ConfigMap에서 환경변수를 가져와서 컨테이너에 적용
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: MYSQL_PASSWORD
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: MYSQL_HOST
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: REDIS_HOST
          volumeMounts:
            - name: ncdata-pv
              mountPath: "/var/www/html"  # /var/www/html에 PV를 마운트
      volumes:
        - name: ncdata-pv
          persistentVolumeClaim:
            claimName: ncdata-pvc  # vol.yaml에서 정의한 PVC를 사용
---
apiVersion: v1
kind: Service   # 서비스 정의
metadata:
  name: nextcloud-service
spec:
  type: NodePort  # NodePort 타입의 서비스를 생성
  ports:
    - port: 80
      #targetPort: 80
      nodePort: 32000  # 호스트의 32000 포트를 컨테이너의 80 포트로 연결
  selector:
    app: nextcloud  # nexcloud 포드에 대한 트래픽을 라우팅

