apiVersion: apps/v1
kind: Deployment

metadata:
  name: dpy-hname
  labels:
    app: hostname
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hostname
  template:
    metadata:
      labels:
        app: hostname
    spec:
      containers:
        - name: hname
          image: sonatinen/hostname:1.0
          ports:
            - containerPort: 80
